language: python

python:
  - "3.4"

services:
  - mysql

env:
  -DJANGO=1.8.3 DB=mysql
  -DJANGO=1.8.3 DB=sqlite3

install:
  - pip install -r requirements.txt
  - pip install mysql-python --use-mirrors

script:
  - python manage.py test
  - coverage run --source=accounts,dashboard,piebase,project,reports manage.py test

after_success:
  coveralls
